### ISSUE TITLE
Chart type support tracker

### ISSUE THREAD

**Issue by dancoates** [bigdatr/pnut#32]
Below is a list of charts that pnut should be able to handle. We don't need to build all of these right now but do need to consider how the pnut API will support them. If you come across any others, comment below and I'll add it to the list.

- [x] Emojis for scatter dots - [pnut example](https://cloud.githubusercontent.com/assets/1946998/23191783/b5e48c9a-f8f3-11e6-96eb-aebd79045000.png)
- [x] Place axis in middle of chart - [example](https://cloud.githubusercontent.com/assets/1946998/23191805/cd91374e-f8f3-11e6-897a-bf7e469e7165.png)
- [x] Stacked line chart (streamgraph) - [example](https://bl.ocks.org/mbostock/4060954)
- [x] Stacked bar chart - [example](http://bl.ocks.org/mbostock/3943967)
- [x] Grouped bar chart - [example](http://bl.ocks.org/mbostock/3943967)
- [ ] Box and whisker/ candlestick plot: [example](https://bl.ocks.org/mbostock/4061502)
- [ ] Choropleth [example](https://bl.ocks.org/mbostock/4060606)
- [ ] Donut/Pie Chart [example](https://bl.ocks.org/mbostock/3887193)
- [ ] Bilevel Partition - [example](https://bl.ocks.org/mbostock/5944371)
- [ ] Github style calendar chart - [example](https://bl.ocks.org/mbostock/4063318)
- [ ] Punch card chart - [example](https://github.com/bigdatr/pnut/graphs/punch-card)
